export const personList = [{
        id: "e8123666baeac108d3d2d2a3a6861760",
        firstName: "Alexandr",
        lastName: "Hamabrdzumyan",
        phone: "+374 93 11 44 15",
        email: "alexanhambarcumyan@gmail.com",
        education: "Shushi Technology university",
        workExperience: "AIPC",
        trainings: "RELQ school",
        imagePath: "./brief_4/imageAlexandrHamabrdzumyan.jpg",
    },
    {
        id: "d01cb0c655ea348f87f9c01289a36ec9",
        firstName: "Anahit",
        lastName: "Khechumyan",
        phone: "+374 44 14 80 00",
        email: "Khechumyan63@gmail.com",
        education: "Yerevan State University",
        workExperience: "School Principal-School N67 Bitschool",
        trainings: "RELQ",
        imagePath: "./brief_4/imageAnahitKhechumyan.jpg",
    },
    {
        id: "a59b7431671af2a5d5dd9aaba6c4f600",
        firstName: "Ani",
        lastName: "Antonyan",
        phone: "not Defined",
        email: "not Defined",
        education: "not Defined",
        workExperience: "not Defined",
        trainings: "RELQ",
        imagePath: "./brief_4/imageAniAntonyan.jpg",
    },
    {
        id: "d16503e5e302427c897cf706d17fa129",
        firstName: "Anna",
        lastName: "Hayriyan",
        phone: "+374 98 14 44 50",
        email: "annhayriyan@gmail.com",
        education: "ASUE",
        workExperience: "Scott logistics",
        trainings: "RELQ",
        imagePath: "./brief_4/imageAnnaHayriyan.jpg",
    },
    {
        id: "e91123d91028cbcea8ab90e6ef8e2a9e",
        firstName: "Armenak",
        lastName: "Qocharyan",
        phone: "+374 94 90 21 71",
        email: "qocharyanarmenak@gmail.com",
        education: "high Army",
        workExperience: "ՀՀ ՊՆ",
        trainings: "Relq School",
        imagePath: "./brief_4/imageArmenakQocharyan.jpg",
    },
    {
        id: "9c6eb8e476cbeff48792ae5df9f69ec9",
        firstName: "Arusyak",
        lastName: "Aghajanyan",
        phone: "+374 55 90 01 55",
        email: "aghajanyanarusyak@gmail.com",
        education: "YSUGU",
        workExperience: "InecoBank CJSC, Risk meneger",
        trainings: "BasicItCenter,UNDP Armenia Accelerator5,HTI Armenia C++ basic, SmartCode,Relq Technology",
        imagePath: "./brief_4/imageArusyakAghajanyan.jpg",
    },
    {
        id: "d8449a0b73fd8eadd8ee890d070a3953",
        firstName: "Afina",
        lastName: "Panyan",
        phone: "not Defined",
        email: "not Defined",
        education: "not Defined",
        workExperience: "not Defined",
        trainings: "Relq",
        imagePath: "./brief_4/imageAfinaPanyan.jpg",
    },
    {
        id: "c583221f2fa2c151cfbdcd8a0ca69835",
        firstName: "Babken",
        lastName: "Tadevosyan",
        phone: "+374 93 28 55 95",
        email: "not Defined",
        education: "not Defined",
        workExperience: "not Defined",
        trainings: "Relq",
        imagePath: "./brief_4/imageBabkenTadevosyan.jpg",
    },
    {
        id: "85cdbb3afd2daf31c92a68e39a6e85ca",
        firstName: "Hasmik",
        lastName: "Gevorgyan",
        phone: "not Defined",
        email: "not Defined",
        education: "not Defined",
        workExperience: "not Defined",
        trainings: "Relq",
        imagePath: "./brief_4/imageHasmikGevorgyan.jpg",
    },
    {
        id: "9e93609305bcea1f8f98475aad68377f",
        firstName: "Hermine",
        lastName: "Melkumyan",
        phone: "not Defined",
        email: "not Defined",
        education: "not Defined",
        workExperience: "not Defined",
        trainings: "Relq",
        imagePath: "./brief_4/imageHermineMelkumyan.jpg",
    },
    {
        id: "cf447d750f6434fdd63ce82f7475db0b",
        firstName: "Hermine",
        lastName: "Sahakyan",
        phone: "not Defined",
        email: "not Defined",
        education: "not Defined",
        workExperience: "not Defined",
        trainings: "Relq",
        imagePath: "./brief_4/imageHermineSahakyan.jpg",
    },
    {
        id: "d135ed21e329652b908e874762c8c9a3",
        firstName: "Larine",
        lastName: "Danielyan",
        phone: "+374 97 75 95 99",
        email: "danielyanlari@gmail.com",
        education: "Economics and Menegment",
        workExperience: "Martuninsky district Medical Association",
        trainings: "Relq",
        imagePath: "./brief_4/imageLarineDanielyan.jpg",
    },
    {
        id: "8d19f167cd820d5bf0019822435bf020",
        firstName: "Liana",
        lastName: "Dashyan",
        phone: "+374 91 55 53 74",
        email: "dashyanlian@gmail.com",
        education: "YSU",
        workExperience: "GYU NGO",
        trainings: "Relq",
        imagePath: "./brief_4/imageLianaDashyan.jpg",
    },
    {
        id: "bc63a6023fb6e44ab80b5f4aafaa4221",
        firstName: "Lusine",
        lastName: "Yeremyan",
        phone: "+374 43 18 18 34",
        email: "lusineer@gmail.com",
        education: "Economist",
        workExperience: "Municipality",
        trainings: "Relq, MIC",
        imagePath: "./brief_4/imageLusineYeremyan.jpg",
    },
    {
        id: "f7231d5724bdec68f3c8a7a5f0e176a0",
        firstName: "Lusine",
        lastName: "Petrosyan",
        phone: "+374 93 32 29 02",
        email: "plusine99@gmail.com",
        education: "Armenian State University faculty of Radiophysics",
        workExperience: "not Defined",
        trainings: "Relq",
        imagePath: "./brief_4/imageLusinePetrosyan.jpg",
    },
    {
        id: "c98b903b4fa91376ae707e489c884140",
        firstName: "Karen",
        lastName: "Darbinyan",
        phone: "+374 98 156 247",
        email: "kar31100@gmail.com",
        education: "YSU",
        workExperience: "alam asxarh",
        trainings: "RELQ",
        imagePath: "./brief_4/imageKarenDarbinyan.jpg",
    },
    {
        id: "c9b9ecdd708d06f4a169dbbcb69c7982",
        firstName: "Marat",
        lastName: "Harutyunyan",
        phone: "+374 44 05 51 50",
        email: "maratharutyunyan.mh.mh@gmail.com",
        education: "ASIPCS",
        workExperience: "EL Market",
        trainings: "Relq School",
        imagePath: "./brief_4/imageMaratHarutyunyan.jpg",
    },
    {
        id: "814705d38a1cd1e3dcb456ec2d0cd770",
        firstName: "Narek",
        lastName: "Tovmasyan",
        phone: "+374 94 27 67 00",
        email: "Narektom333@gmail.com",
        education: "ASUE",
        workExperience: "Ameria Bank",
        trainings: "Relq School",
        imagePath: "./brief_4/imageNarekTovmasyan.jpg",
    },
    {
        id: "c1f084d3adb167a1e17c6c4cd87a51cb",
        firstName: "Seda",
        lastName: "Shahnazaryan",
        phone: "+374 98 31 38 71",
        email: "shahnazaryan.seda@mail.ru",
        education: "Higher Education:Historian",
        workExperience: "not Defined",
        trainings: "TechBoost4Women,RELQ technology school",
        imagePath: "./brief_4/imageSedaShahnazaryan.jpg",
    },
    {
        id: "a5f04c92d921c54cfbbc83bca438fa5d",
        firstName: "Seryozha",
        lastName: "Asatryan",
        phone: "+374 94 24 68 80",
        email: "seryozha.asatryan02@gmail.com",
        education: "Economics",
        workExperience: "not Defined",
        trainings: "Relq School",
        imagePath: "./brief_4/imageSeryozhaAsatryan.jpg",
    },
    {
        id: "8edc98f163146734ec93ab158dba7ad4",
        firstName: "Sevak",
        lastName: "Stepanyan",
        phone: "+374 77 12 16 96",
        email: "stepanyansevak9@gamil.com",
        education: "Economics and Menegment",
        workExperience: "not Defined",
        trainings: "Relq School",
        imagePath: "./brief_4/imageSevakStepanyan.jpg",
    },
    {
        id: "dfc9e4c9249b53bcc3676f35c6c231d4",
        firstName: "Silva",
        lastName: "Ohanyan",
        phone: "not Defined",
        email: "not Defined",
        education: "not Defined",
        workExperience: "not Defined",
        trainings: "Relq School",
        imagePath: "./brief_4/imageSilvaOhanyan.jpg",
    },
    {
        id: "d469c8eaac8bbd68f35b0909d913f8a8",
        firstName: "Suren",
        lastName: "Galstyan",
        phone: "not Defined",
        email: "not Defined",
        education: "not Defined",
        workExperience: "not Defined",
        trainings: "Relq School",
        imagePath: "./brief_4/imageSurenGalstyan.jpg",
    },
    {
        id: "f767786d3d6eadc8c738746f19babd9c",
        firstName: "Tigran",
        lastName: "Martirosyan",
        phone: "+374 77 15 18 68",
        email: "martirosyant01@mail.ru",
        education: "not Defined",
        workExperience: "not Defined",
        trainings: "Relq School",
        imagePath: "./brief_4/imageTigranMartirosyan.jpg",
    },
];